---
output: html_document
---

### Supply Estimates

* Data were provided by TWC from the Frontline Operation list as of May 5, 2020, which indicates the location of child care providers that are currently open.

* We merged the Frontline Operation list with publicly available data from Child Care Licensing to gather total licensed capacity of each child care program currently open in Texas.  Research on industry standards suggests that viable child care programs, on average, aim to have enrollment rates at ~85% of licensed capacity.[1] Hence, we use 85% of licensed capacity as an estimate of the actual capacity, and refer to it as pre-COVID available seats below.

* We created three scenarios for available child care seats:
  - High: 70% of pre-COVID available seats
  - Medium: 50% of pre-COVID available seats
  - Low: 35% of pre-COVID supply.  This is based on a foot traffic data we have analyzed suggesting that child care enrollment is ~25% of what it was pre-COVID.[2]  We assume child care providers can serve more children than current enrollment suggests, but only at 35% of pre-COVID levels. 

* For child care homes that remain open, we assume that all pre-COVID available child care seats are available now given that staffing changes do not impact this segment of child care providers. 
 
### Demand Estimates

* We utilized population data by county from the Census and American Community Survey 1-year estimates (2018), including estimates for the total number of people in the workforce by industry and occupation.  We applied the following assumptions:

* We selected industries relevant to this analysis, beginning with essential industries and adding those recently reopened at reduced capacity.  Please see below for industries and occupations included.

* We take a county’s population and total number of households to estimate the average number of people per household.  We assume that households from our industries of interest follow these typical figures and estimate the total number of households with workers in our industries of interest.

* Census also provides the proportion of the population younger than 18 years old in each county. Assuming uniform distribution across ages younger than 18, we estimate the percent of the population 12 years old or younger. We use this to estimate the number of children under age 12 per 100 households.

* We estimate the number of children who may need child care in our industries of interest by utilizing the number of households with workers in these industries and the rate of children under age 12 per 100 households.

* Finally, we adjust for the fact that some households contain other non-working adults or older sibling that can provide care for some children in the household. 

### Industries and occupations

#### Essential industries

* Health Care & Social Assistance
* Manufacturing
* Educational Services
* Accommodation & Food Services (takeout and delivery only)
* Professional, Scientific, & Technical Services
* Transportation & Warehousing
* Administrative & Support & Waste Management Services
* Wholesale Trade
* Public Administration
* Information
* Utilities

#### Essential occupations

* Transportation Occupations
* Installation, Maintenance, & Repair Occupations
* Farming, Fishing, & Forestry Occupations
* Community & Social Service Occupations
* Education Instruction, & Library Occupations
* Law Enforcement Workers Including Supervisors
* Fire Fighting & Prevention, & Other Protective Service Workers Including Supervisors
* Health Diagnosing & Treating Practitioners & Other Technical Occupations
* Personal Care & Service Occupations
* Health Technologists & Technicians
* Building & Grounds Cleaning & Maintenance Occupations
* Healthcare Support Occupations
* Food Preparation & Serving Related Occupations (takeout and delivery only)

#### Re-opening phase 1 industries (at 25% capacity) added to essential industries:

* Retail trade and arts
* Entertainment and recreation
* Accommodation & food services


#### Re-opening phase 1 occupations (at 25% capacity) added to essential occupations:

* Sales and related occupations
* Arts, Design, Entertainment, Sports, & Media Occupations
* Food Preparation & Serving Related Occupations

 
[1] https://childcareta.acf.hhs.gov/sites/default/files/public/241_1411_pcqc_ece_characteristics_final.pdf

[2] Professor Flavio Cunha, one of the Lab’s Faculty Affiliates, has secured access to de-identified cell phone data owned by SafeGraph. This data allows researchers to observe the amount of mobility in each Public Use Microdata Area. This mobility data is highly correlated with economic activity.  We are building a model to link economic activity with childcare needs.